### ISSUE TITLE
Job lib error with 'i' format 

### ISSUE THREAD

**Issue by naadvar** [ing-bank/probatus#168]
Hi all,

I get the following issue when running the following code

```
shap_elimination = ShapRFECV(
    clf=search, step=0.2, cv=5, scoring='neg_log_loss', n_jobs=-1,verbose=100,random_state=44)
report = shap_elimination.fit(x_train, y_train['total_attrition'],columns_to_keep=columns_to_keep_rn)
```

This is the traceback from the error:

```
"""
Traceback (most recent call last):
  File "/home/uex694/.local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 360, in _sendback_result
    exception=exception))
  File "/home/uex694/.local/lib/python3.7/site-packages/joblib/externals/loky/backend/queues.py", line 247, in put
    self._writer.send_bytes(obj)
  File "/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""

The above exception was the direct cause of the following exception:
```

I tried updgrading/reinstalling joblib and also tried changing based on this [https://github.com/scikit-learn/scikit-learn/issues/3313 ](https://github.com/scikit-learn/scikit-learn/issues/3313) but was still not able to resolve the issue in this case

**Comment by ReinierKoops** [comment]
Can you provide more info?

**Comment by ReinierKoops** [comment]
Please feel free to make another issue when this is encountered again. I believe it should be fixed in the latest version.
