### ISSUE TITLE
Mkdocs fails

### ISSUE THREAD

**Issue by ReinierKoops** [ing-bank/probatus#224]
**Describe the bug**
The action for releasing the latest probatus version failed on MKDOCS.

**To Reproduce**

Run the release action

**Error traceback**

If applicable please provide full traceback of the error.

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.12/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 310, in gh_deploy_command
    cfg = config.load_config(remote_branch=remote_branch, remote_name=remote_name, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mkdocs/config/base.py", line 378, in load_config
    errors, warnings = cfg.validate()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mkdocs/config/base.py", line [23](https://github.com/ing-bank/probatus/actions/runs/5681820734/job/15398792261#step:7:24)0, in validate
    run_failed, run_warnings = self._validate()
File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mkdocs/config/base.py", line 188, in _validate
    self[key] = config_option.validate(value)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 182, in validate
    return self.run_validation(value)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1054, in run_validation
    self.load_plugin_with_namespace(name, cfg)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1090, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1108, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 2[41](https://github.com/ing-bank/probatus/actions/runs/5681820734/job/15398792261#step:7:42), in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mknotebooks/plugin.py", line 17, in <module>
    from mkdocs.structure.pages import Page, _RelativePathExtension
ImportError: cannot import name '_RelativePathExtension' from 'mkdocs.structure.pages' (/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mkdocs/structure/pages.py)
Error: Process completed with exit code 1.
```

**Expected behavior**

This should not happen. A suggestion for a fix would be to reimplement mkdocs, since now we are using a lot of potentially outdated MKDOCS functions.

**Comment by ReinierKoops** [comment]
Does not seem like it.
